# Generated by Django 3.2.12 on 2022-04-03 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmonitor',
            name='pulgadas',
            field=models.DecimalField(decimal_places=1, default=15, max_digits=3),
        ),
        migrations.AddField(
            model_name='monitor',
            name='pulgadas',
            field=models.DecimalField(decimal_places=1, default=15, max_digits=3),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('marca', models.CharField(db_index=True, default='', max_length=15)),
                ('modelo', models.CharField(db_index=True, default='', max_length=15)),
                ('precio_amazon_EEUU', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('clasificacion_amazon_EEUU', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('link_amazon_EEUU', models.URLField()),
                ('raytracing', models.BooleanField(verbose_name='Tiene procesador de Raytracing?')),
                ('cambio_gpu_dinamico', models.BooleanField(verbose_name='Tiene cambio de GPU dinámico?')),
                ('mux_switch', models.BooleanField(verbose_name='Tiene cambio de salida pantalla?')),
                ('refresco_pantalla_adaptativo', models.BooleanField(verbose_name='Tiene refresco de pantalla adaptativo (Freesync o G-Sync)?')),
                ('thunderbol_3_4', models.BooleanField(verbose_name='Tiene algún puerto thunderbol 3 o 4?')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.cpu')),
                ('disco_duro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.disco_duro')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.gpu')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.monitor')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.ram')),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptops',
                'ordering': ('marca', 'modelo', 'precio_amazon_EEUU'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalLaptop',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('marca', models.CharField(db_index=True, default='', max_length=15)),
                ('modelo', models.CharField(db_index=True, default='', max_length=15)),
                ('precio_amazon_EEUU', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('clasificacion_amazon_EEUU', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('link_amazon_EEUU', models.URLField()),
                ('raytracing', models.BooleanField(verbose_name='Tiene procesador de Raytracing?')),
                ('cambio_gpu_dinamico', models.BooleanField(verbose_name='Tiene cambio de GPU dinámico?')),
                ('mux_switch', models.BooleanField(verbose_name='Tiene cambio de salida pantalla?')),
                ('refresco_pantalla_adaptativo', models.BooleanField(verbose_name='Tiene refresco de pantalla adaptativo (Freesync o G-Sync)?')),
                ('thunderbol_3_4', models.BooleanField(verbose_name='Tiene algún puerto thunderbol 3 o 4?')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cpu', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='principal.cpu')),
                ('disco_duro', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='principal.disco_duro')),
                ('gpu', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='principal.gpu')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('monitor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='principal.monitor')),
                ('ram', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='principal.ram')),
            ],
            options={
                'verbose_name': 'historical Laptop',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
