# Generated by Django 3.2.12 on 2022-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20220403_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='frecuencia',
            field=models.IntegerField(default=1024),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='nucleos',
            field=models.IntegerField(default=1024),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='frecuencia',
            field=models.IntegerField(default=1024),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='nucleos',
            field=models.IntegerField(default=1024),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='modelo',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='modelo',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
    ]
