# Generated by Django 3.2.12 on 2022-04-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20220403_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='frecuencia_nucleos_fuertes_all',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=2),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='gama',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('7', '7'), ('9', '9')], default='7', max_length=1),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='generacion',
            field=models.CharField(default='11', max_length=2),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='hilos',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='modelo',
            field=models.CharField(default='800', max_length=3),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='nucleos_fuertes',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='pcie_version',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='disco_duro',
            name='capacidad_GB',
            field=models.IntegerField(default=512),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='cant_vram_GB',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='frecuencia',
            field=models.IntegerField(default=1425),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='generacion',
            field=models.CharField(default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='modelo',
            field=models.CharField(default='060', max_length=3),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='nucleos',
            field=models.IntegerField(default=3840),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='pcie_version',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='tpd_w',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='frecuencia_nucleos_fuertes_all',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=2),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='gama',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('7', '7'), ('9', '9')], default='7', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='generacion',
            field=models.CharField(default='11', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='hilos',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='modelo',
            field=models.CharField(default='800', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='nucleos_fuertes',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='pcie_version',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='historicaldisco_duro',
            name='capacidad_GB',
            field=models.IntegerField(default=512),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='cant_vram_GB',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='frecuencia',
            field=models.IntegerField(default=1425),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='generacion',
            field=models.CharField(default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='modelo',
            field=models.CharField(default='060', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='nucleos',
            field=models.IntegerField(default=3840),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='pcie_version',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='tpd_w',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='historicalmonitor',
            name='hdr',
            field=models.CharField(choices=[('0', ':NO'), ('1', '400'), ('2', '500'), ('3', '600'), ('4', '1000'), ('5', '1400')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalram',
            name='generacion',
            field=models.CharField(choices=[('1', 'DDR'), ('2', 'DDR2'), ('3', 'DDR3'), ('4', 'DDR4'), ('5', 'DDR5')], default='4', max_length=1),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='hdr',
            field=models.CharField(choices=[('0', ':NO'), ('1', '400'), ('2', '500'), ('3', '600'), ('4', '1000'), ('5', '1400')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='ram',
            name='generacion',
            field=models.CharField(choices=[('1', 'DDR'), ('2', 'DDR2'), ('3', 'DDR3'), ('4', 'DDR4'), ('5', 'DDR5')], default='4', max_length=1),
        ),
    ]
