# Generated by Django 3.2.12 on 2022-04-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20220403_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallaptop',
            name='thunderbol_3_4',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='thunderbol_3_4',
        ),
        migrations.AddField(
            model_name='historicallaptop',
            name='thunderbolt_3_4',
            field=models.BooleanField(default=False, verbose_name='Tiene algún puerto thunderbolt 3 o 4?'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='thunderbolt_3_4',
            field=models.BooleanField(default=False, verbose_name='Tiene algún puerto thunderbolt 3 o 4?'),
        ),
    ]
