# Generated by Django 3.2.12 on 2022-04-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20220403_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallaptop',
            name='serie',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='serie',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='marca',
            field=models.CharField(db_index=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='modelo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='marca',
            field=models.CharField(db_index=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='modelo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, null=True),
        ),
    ]
