# Generated by Django 3.2.12 on 2022-04-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20220403_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmonitor',
            name='espacio_DCI_P3',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='espacio_DCI_P3',
        ),
    ]
