# Generated by Django 3.2.12 on 2022-04-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20220403_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='nombre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcpu',
            name='nombre',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='clasificacion_amazon_EEUU',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Clasificación de Amazon'),
        ),
        migrations.AlterField(
            model_name='historicallaptop',
            name='precio_amazon_EEUU',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='clasificacion_amazon_EEUU',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Clasificación de Amazon'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='precio_amazon_EEUU',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio'),
        ),
    ]
