# Generated by Django 3.2.12 on 2022-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20220406_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Puntuación'),
        ),
        migrations.AddField(
            model_name='historicalcpu',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Puntuación'),
        ),
    ]
