# Generated by Django 3.2.12 on 2022-04-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20220406_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='nombre',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='gpu',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Puntuación'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='tipo',
            field=models.CharField(default='RTX', max_length=3),
        ),
        migrations.AddField(
            model_name='historicalgpu',
            name='nombre',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='historicalgpu',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Puntuación'),
        ),
        migrations.AddField(
            model_name='historicalgpu',
            name='tipo',
            field=models.CharField(default='RTX', max_length=3),
        ),
    ]
