# Generated by Django 3.2.12 on 2022-04-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_auto_20220406_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='nombre',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='nombre',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
