# Generated by Django 3.2.12 on 2022-04-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20220406_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalram',
            name='nombre',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalram',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Puntuación'),
        ),
        migrations.AddField(
            model_name='ram',
            name='nombre',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='nombre',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='nombre',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
