# Generated by Django 3.2.12 on 2022-04-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20220406_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco_duro',
            name='nombre',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='disco_duro',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Puntuación'),
        ),
        migrations.AddField(
            model_name='historicaldisco_duro',
            name='nombre',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicaldisco_duro',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Puntuación'),
        ),
    ]
