# Generated by Django 3.2.12 on 2022-04-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_auto_20220406_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallaptop',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Puntuación'),
        ),
    ]
