# Generated by Django 3.2.12 on 2022-04-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_auto_20220406_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallaptop',
            name='calidad_precio',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Calidad/precio'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='calidad_precio',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Calidad/precio'),
        ),
    ]
