# Generated by Django 3.2.12 on 2022-04-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0020_auto_20220406_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='disco_duro',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='historicaldisco_duro',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='historicalmonitor',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='historicalram',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Puntuación'),
        ),
        migrations.AlterField(
            model_name='ram',
            name='puntuacion_save',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Puntuación'),
        ),
    ]
