# Generated by Django 3.2.12 on 2022-04-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_game_historicalgame_historicalrendimiento_rendimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrendimiento',
            name='fps_review',
            field=models.BooleanField(default=True, verbose_name='Fue obtenido por review?'),
        ),
        migrations.AddField(
            model_name='rendimiento',
            name='fps_review',
            field=models.BooleanField(default=True, verbose_name='Fue obtenido por review?'),
        ),
    ]
