# Generated by Django 3.2.12 on 2022-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_auto_20220414_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallaptop',
            name='link_notebookcheck',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='link_notebookcheck',
            field=models.URLField(blank=True, null=True),
        ),
    ]
