# Generated by Django 3.2.12 on 2022-04-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0026_auto_20220416_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cinebench_R23_multi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cinebench_R23_single',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcpu',
            name='cinebench_R23_multi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcpu',
            name='cinebench_R23_single',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalrendimiento',
            name='nombre',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Laptop'),
        ),
        migrations.AlterField(
            model_name='rendimiento',
            name='nombre',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Laptop'),
        ),
    ]
