# Generated by Django 3.2.12 on 2022-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0027_auto_20220417_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cache_L2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cache_L3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cache_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='cache_L2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='cache_L3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpu',
            name='cache_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcpu',
            name='cache_L2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcpu',
            name='cache_L3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcpu',
            name='cache_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalgpu',
            name='cache_L2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalgpu',
            name='cache_L3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalgpu',
            name='cache_total',
            field=models.IntegerField(default=0),
        ),
    ]
