# Generated by Django 3.2.12 on 2022-04-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0028_auto_20220418_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='cache_L2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache L2'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cache_L3',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache L3'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='cache_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache total'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='cache_L2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache L2'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='cache_L3',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache L3'),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='cache_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache total'),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='cache_L2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache L2'),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='cache_L3',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache L3'),
        ),
        migrations.AlterField(
            model_name='historicalcpu',
            name='cache_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache total'),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='cache_L2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache L2'),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='cache_L3',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache L3'),
        ),
        migrations.AlterField(
            model_name='historicalgpu',
            name='cache_total',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cache total'),
        ),
    ]
